apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-gateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Install before agent-gateway
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/kgateway-dev/charts
    chart: agentgateway-crds
    targetRevision: v2.2.0-main
  
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # Allow CRD replacement
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
