apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Terraform Health Check for Tofu Controller
  # This tells ArgoCD to wait for Terraform resources to complete before proceeding to next sync wave
  resource.customizations.health.infra.contrib.fluxcd.io_Terraform: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.plan ~= nil and obj.status.plan.pending ~= nil then
        hs.status = "Progressing"
        hs.message = "Terraform plan pending"
        return hs
      end
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = "Terraform applied successfully"
            return hs
          end
          if condition.type == "Ready" and condition.status == "False" then
            hs.status = "Degraded"
            hs.message = condition.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for Terraform to complete"
    return hs
