apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.projectName }}-mcp-sa
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: agent-core-mcp-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: agent-core-mcp-{{ .Values.version }}
  ports:
    - port: 8080
      targetPort: 8080
      name: mcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-core-mcp-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-core-mcp-{{ .Values.version }}
  template:
    metadata:
      labels:
        app: agent-core-mcp-{{ .Values.version }}
    spec:
      serviceAccountName: {{ .Values.projectName }}-mcp-sa
      containers:
      - name: mcp-server
        image: {{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag }}
        imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: mcp
        env:
        - name: AWS_REGION
          value: {{ .Values.awsRegion }}
        - name: MEMORY_ID
          valueFrom:
            secretKeyRef:
              name: agent-core-outputs-{{ .Values.version }}
              key: memory_id
        - name: BROWSER_ID
          valueFrom:
            secretKeyRef:
              name: agent-core-outputs-{{ .Values.version }}
              key: browser_id
        - name: CODE_INTERPRETER_ID
          valueFrom:
            secretKeyRef:
              name: agent-core-outputs-{{ .Values.version }}
              key: code_interpreter_id
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
