apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: mcp-server-backend
  namespace: {{ .Values.namespace }}
spec:
  static:
    hosts:
      - host: mcp-server-service.{{ .Values.namespace }}.svc.cluster.local
        port: 8000
