apiVersion: kagent.amazon.com/v1alpha2
kind: RemoteMCPServer
metadata:
  name: agent-core-tools-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  url: http://agent-core-mcp-{{ .Values.version }}:8080/mcp
  description: "Agent Core capabilities: Memory, Browser, Code Interpreter"
  tools:
    - name: get_weather_data
      description: "Get weather data for a city using browser automation"
    - name: generate_analysis_code
      description: "Generate Python code for weather classification"
    - name: execute_code
      description: "Execute Python code using Agent Core Code Interpreter"
    - name: store_user_preferences
      description: "Store user activity preferences in memory"
    - name: get_activity_preferences
      description: "Get user activity preferences from memory"
    - name: store_activity_plan
      description: "Store the activity plan in memory for future reference"
