apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: agent-core-tools-{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  url: http://agent-gateway-proxy.agentgateway-system.svc.cluster.local:8080/mcp
  description: "Agent Core capabilities: Memory, Browser, Code Interpreter"
  protocol: STREAMABLE_HTTP
  timeout: 30s
  headersFrom:
    - name: Authorization
      valueFrom:
        type: Secret
        name: {{ .Values.projectName }}-agent-sa-token
        key: token
