apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-gateway-token-reviewer
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]
