apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: tracing-policy
  namespace: agentgateway-system
spec:
  targetRefs:
    - kind: Gateway
      name: agent-gateway-proxy
      group: gateway.networking.k8s.io
  frontend:
    tracing:
      backendRef:
        name: jaeger-otlp
        namespace: agentgateway-system
        port: 4317
      protocol: GRPC
      clientSampling: "true"
      randomSampling: "true"
      resources:
        - name: service.name
          expression: '"agent-gateway"'
        - name: deployment.environment
          expression: '"eks-dev"'
      attributes:
        add:
          - name: agent.identity
            expression: 'request.headers["x-agent-identity"]'
          - name: tool.name
            expression: 'request.headers["x-tool-name"]'
